# Generated by Django 5.2.4 on 2025-07-18 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'BookCategory',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(max_length=20, null=True)),
                ('case_number', models.CharField(max_length=20, null=True)),
                ('appellant', models.CharField(max_length=255, null=True)),
                ('respondent', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('court', models.CharField(choices=[('TRAB', 'TRAB'), ('TRAT', 'TRAT'), ('CAT', 'CAT'), ('HCT', 'HCT'), ('UGANDA SUPREME COURT', 'UGANDA SUPREME COURT'), ('KENYA SUPREME COURT', 'KENYA SUPREME COURT'), ('UK SUPREME COURT', 'UK SUPREME COURT'), ('INDIA SUPREME COURT', 'INDIA SUPREME COURT'), ('AUSTRALIA SUPREME COURT', 'AUSTRALIA SUPREME COURT')], max_length=30, null=True)),
                ('tax_type', models.CharField(choices=[('Income Tax', 'Income Tax'), ('Value Added Tax', 'Value Added Tax'), ('Excise Duty', 'Excise Duty'), ('Import Duty', 'Import Duty'), ('Skills and Development Levy', 'Skills and Development Levy'), ('Airport Departure Charges', 'Airport Departure Charges'), ('Port Departure Charges', 'Port Departure Charges'), ('Stamp Duty', 'Stamp Duty'), ('Other', 'Other')], max_length=30, null=True)),
                ('tax_court', models.CharField(choices=[('Tax Revenue Appeals Board', 'Tax Revenue Appeals Board'), ('Tax Revenue Appeals Tribunal', 'Tax Revenue Appeals Tribunal'), ('Court of Appeal of Tanzania', 'Court of Appeal of Tanzania'), ('High Court of Tanzania', 'High Court of Tanzania')], max_length=50, null=True)),
                ('originating_cases', models.TextField(max_length=255, null=True)),
                ('year', models.IntegerField(choices=[(1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], default=2025)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='cases/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('collaborator_name', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('collaborator_phone', models.CharField(default='', max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('URGENT', 'Urgent'), ('NORMAL', 'Normal'), ('NOT URGENT', 'Not Urgent')], default='NOT URGENT', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(choices=[(1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], default=2025)),
                ('sensitivity', models.CharField(choices=[('critical', 'critical'), ('not_critical', 'Not Critical')], default='not_critical', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='docs.bookcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
