# Generated by Django 5.1.3 on 2024-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_bookcategory_alter_messages_status_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sensitivity',
            field=models.CharField(choices=[('critical', 'critical'), ('not_critical', 'Not Critical')], default='not_critical', max_length=20),
        ),
    ]
