# Generated by Django 4.2.4 on 2024-09-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('URG', 'Urgent'), ('NOR', 'Normal'), ('NUR', 'Not Urgent')], default='NUR', max_length=3),
        ),
    ]
