# Generated by Django 5.1.3 on 2024-12-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_book_sensitivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Dodoma', 'Dodoma'), ('Temeke', 'Temeke'), ('Arusha', 'Arusha')], max_length=50)),
                ('district', models.CharField(choices=[('Kondoa', 'Kondoa'), ('Chemba', 'Chemba'), ('Dodoma Urban', 'Dodoma Urban'), ('Bahi', 'Bahi'), ('Congwa', 'Congwa'), ('Mpwapwa', 'Mpwapwa'), ('Chamwino', 'Chamwino'), ('Kinondoni', 'Kinondoni'), ('Ilala', 'Ilala'), ('Ubungo', 'Ubungo'), ('Kigamboni', 'Kigamboni'), ('Kurasini', 'Kurasini'), ('Karatu', 'Karatu'), ('Longido', 'Longido'), ('Meru', 'Meru'), ('Monduli', 'Monduli'), ('Ngorongoro', 'Ngorongoro')], max_length=50)),
                ('township', models.CharField(choices=[('Bolisa', 'Bolisa'), ('Chemchem', 'Chemchem'), ('Kilimani', 'Kilimani'), ('Kingale', 'Kingale'), ('Kolo', 'Kolo'), ('Kondoa Mjini', 'Kondoa Mjini'), ('Serya', 'Serya'), ('Suruke', 'Suruke'), ('Babayu', 'Babayu'), ('Chandama', 'Chandama'), ('Chemba', 'Chemba'), ('Churuku', 'Churuku'), ('Chali', 'Chali'), ('Chibelela', 'Chibelela'), ('Chifutuka', 'Chifutuka'), ('Chikola', 'Chikola'), ('Chipanga', 'Chipanga'), ('Ibihwa', 'Ibihwa'), ('Buguruni', 'Buguruni'), ('Buyuni', 'Buyuni'), ('Chanika', 'Chanika'), ('Gerezani', 'Gerezani'), ('Goba', 'Goba'), ('Kibamba', 'Kibamba'), ('Kimara', 'Kimara'), ('Kwembe', 'Kwembe'), ('Akheri', 'Akheri'), ('Ambureni', 'Ambureni'), ('Imbaseni', 'Imbaseni'), ('Kikatiti', 'Kikatiti'), ('Kikwe', 'Kikwe'), ('Namanga', 'Namanga'), ('Noondoto', 'Noondoto'), ('Olmolog', 'Olmolog'), ('Orbomba', 'Orbomba'), ('Sinya', 'Sinya'), ('Tingatinga', 'Tingatinga')], max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='cases/files/')),
                ('category', models.CharField(choices=[('Criminal', 'Criminal'), ('Civil', 'Civil'), ('Administrative', 'Administrative'), ('Othe', 'Other')], default='Other', max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='agent_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='agent_phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
