# Generated by Django 5.1.4 on 2024-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sensitivity',
            field=models.CharField(choices=[('critical', 'critical'), ('not_critical', 'Not Critical')], default='not_critical', max_length=20),
        ),
    ]
