# Generated by Django 5.1.3 on 2024-12-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_agent_cases_messages_agent_name_messages_agent_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
