# Generated by Django 5.1.3 on 2024-12-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_delete_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='agent_phone',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='location',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='phone',
        ),
    ]
