# Generated by Django 5.1.4 on 2024-12-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='agent_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='agent_phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='district',
            field=models.CharField(choices=[('Kondoa', 'Kondoa'), ('Chemba', 'Chemba'), ('Dodoma Urban', 'Dodoma Urban'), ('Bahi', 'Bahi'), ('Congwa', 'Congwa'), ('Mpwapwa', 'Mpwapwa'), ('Chamwino', 'Chamwino'), ('Kinondoni', 'Kinondoni'), ('Ilala', 'Ilala'), ('Ubungo', 'Ubungo'), ('Kigamboni', 'Kigamboni'), ('Kurasini', 'Kurasini'), ('Karatu', 'Karatu'), ('Longido', 'Longido'), ('Meru', 'Meru'), ('Monduli', 'Monduli'), ('Ngorongoro', 'Ngorongoro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='township',
            field=models.CharField(choices=[('Bolisa', 'Bolisa'), ('Chemchem', 'Chemchem'), ('Kilimani', 'Kilimani'), ('Kingale', 'Kingale'), ('Kolo', 'Kolo'), ('Kondoa Mjini', 'Kondoa Mjini'), ('Serya', 'Serya'), ('Suruke', 'Suruke'), ('Babayu', 'Babayu'), ('Chandama', 'Chandama'), ('Chemba', 'Chemba'), ('Churuku', 'Churuku'), ('Chali', 'Chali'), ('Chibelela', 'Chibelela'), ('Chifutuka', 'Chifutuka'), ('Chikola', 'Chikola'), ('Chipanga', 'Chipanga'), ('Ibihwa', 'Ibihwa'), ('Buguruni', 'Buguruni'), ('Buyuni', 'Buyuni'), ('Chanika', 'Chanika'), ('Gerezani', 'Gerezani'), ('Goba', 'Goba'), ('Kibamba', 'Kibamba'), ('Kimara', 'Kimara'), ('Kwembe', 'Kwembe'), ('Akheri', 'Akheri'), ('Ambureni', 'Ambureni'), ('Imbaseni', 'Imbaseni'), ('Kikatiti', 'Kikatiti'), ('Kikwe', 'Kikwe'), ('Namanga', 'Namanga'), ('Noondoto', 'Noondoto'), ('Olmolog', 'Olmolog'), ('Orbomba', 'Orbomba'), ('Sinya', 'Sinya'), ('Tingatinga', 'Tingatinga')], max_length=50),
        ),
    ]
