# Generated by Django 5.1.4 on 2024-12-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_messages_agent_name_messages_agent_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='district',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='township',
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(choices=[('01', 'Arusha'), ('02', 'Dodoma'), ('03', 'Geita'), ('04', 'Ilala'), ('05', 'Iringa'), ('06', 'Kagera'), ('07', 'Katavi'), ('08', 'Kigoma'), ('09', 'Kilimanjaro'), ('10', 'Kinondoni'), ('11', 'Lindi'), ('12', 'Manyara'), ('13', 'Mara'), ('14', 'Mbeya'), ('15', 'Morogoro'), ('16', 'Mtwara'), ('17', 'Mwanza'), ('18', 'Njombe'), ('19', 'Pemba North'), ('20', 'Pemba South'), ('21', 'Pwani'), ('22', 'Rukwa'), ('23', 'Ruvuma'), ('24', 'Shinyanga'), ('25', 'Simiyu'), ('26', 'Singida'), ('27', 'Songwe'), ('28', 'Tabora'), ('29', 'Tanga'), ('30', 'Temeke')], max_length=2),
        ),
    ]
