# Generated by Django 5.1.3 on 2024-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_delete_cases_remove_messages_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='agent_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='agent_phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
