# Generated by Django 5.1.3 on 2024-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_messages_agent_name_messages_agent_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('01', 'Arusha'), ('02', 'Dodoma'), ('03', 'Geita'), ('04', 'Ilala'), ('05', 'Iringa'), ('06', 'Kagera'), ('07', 'Katavi'), ('08', 'Kigoma'), ('09', 'Kilimanjaro'), ('10', 'Kinondoni'), ('11', 'Lindi'), ('12', 'Manyara'), ('13', 'Mara'), ('14', 'Mbeya'), ('15', 'Morogoro'), ('16', 'Mtwara'), ('17', 'Mwanza'), ('18', 'Njombe'), ('19', 'Pemba North'), ('20', 'Pemba South'), ('21', 'Pwani'), ('22', 'Rukwa'), ('23', 'Ruvuma'), ('24', 'Shinyanga'), ('25', 'Simiyu'), ('26', 'Singida'), ('27', 'Songwe'), ('28', 'Tabora'), ('29', 'Tanga'), ('30', 'Temeke'), ('31', 'Unguja North'), ('32', 'Unguja South'), ('33', 'Zanzibar City')], max_length=2)),
                ('agent_code', models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='agent_name',
            new_name='agent_code',
        ),
    ]
