# Generated by Django 5.1.4 on 2024-12-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_remove_agent_district_remove_agent_township_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
