# Generated by Django 5.1.3 on 2025-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_agent_rename_agent_name_messages_agent_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, null=True)),
                ('plaintiff', models.CharField(max_length=255, null=True)),
                ('defendant', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('tax_type', models.CharField(choices=[('Income Tax', 'Income Tax'), ('Value Added Tax', 'Value Added Tax'), ('Excise Duty', 'Excise Duty'), ('Import Duty', 'Import Duty'), ('Skills and Development Levy', 'Skills and Development Levy'), ('Airport Departure Charges', 'Airport Departure Charges'), ('Port Departure Charges', 'Port Departure Charges'), ('Stamp Duty', 'Stamp Duty'), ('Other', 'Other')], max_length=30, null=True)),
                ('tax_court', models.CharField(choices=[('Tax Revenue Appeals Board', 'Tax Revenue Appeals Board'), ('Tax Revenue Appeals Tribunal', 'Tax Revenue Appeals Tribunal'), ('Court of Appeal of Tanzania', 'Court of Appeal of Tanzania'), ('High Court of Tanzania', 'High Court of Tanzania')], max_length=50, null=True)),
                ('registry', models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pwani', 'Pwani'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Simiyu', 'Simiyu'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Mjini Magharibi', 'Mjini Magharibi'), ('Kaskazini Unguja', 'Kaskazini Unguja'), ('Kusini Unguja', 'Kusini Unguja'), ('Kaskazini Pemba', 'Kaskazini Pemba'), ('Kusini Pemba', 'Kusini Pemba')], max_length=30, null=True)),
                ('originating_cases', models.TextField(max_length=255, null=True)),
                ('year', models.IntegerField(choices=[(1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], default=2025)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='cases/files/')),
            ],
        ),
    ]
