# Generated by Django 5.1.4 on 2024-12-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_agent_agent_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='agent_name',
            new_name='agent_code',
        ),
    ]
