# Generated by Django 5.1.4 on 2025-01-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_remove_cases_category_remove_cases_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='metadata',
        ),
    ]
