# Generated by Django 5.1.3 on 2025-02-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_rename_defendant_cases_appealant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='appealant',
            new_name='appellant',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='court_code',
            new_name='case_code',
        ),
    ]
