# Generated by Django 5.1.4 on 2025-01-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_cases_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='tax_category',
            field=models.CharField(choices=[('TRAB', 'TRAB'), ('TRAT', 'TRAT'), ('CAT', 'CAT')], max_length=30, null=True),
        ),
    ]
