# Generated by Django 5.1.3 on 2025-03-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_rename_appealant_cases_appellant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='tax_category',
            new_name='court',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='respondant',
            new_name='respondent',
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
