# Generated by Django 5.1.3 on 2025-04-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_rename_tax_category_cases_court_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='file_path',
            field=models.FileField(max_length=500, upload_to='cases/files/'),
        ),
    ]
