# Generated by Django 5.1.4 on 2025-01-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_book_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='plaintiff',
            new_name='appellant',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='registry',
        ),
        migrations.AddField(
            model_name='cases',
            name='court_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='tax_category',
            field=models.CharField(choices=[('TRAB', 'TRAB'), ('TRAT', 'TRAT'), ('CAT', 'CAT'), ('HCT', 'HCT'), ('UGANDA SUPREME COURT', 'UGANDA SUPREME COURT'), ('KENYA SUPREME COURT', 'KENYA SUPREME COURT'), ('UK SUPREME COURT', 'UK SUPREME COURT'), ('INDIA SUPREME COURT', 'INDIA SUPREME COURT'), ('AUSTRALIA SUPREME COURT', 'AUSTRALIA SUPREME COURT')], max_length=30, null=True),
        ),
    ]
