# Generated by Django 5.1.3 on 2025-07-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_alter_cases_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('01', 'Arusha'), ('02', 'Dar es salaam'), ('03', 'Dodoma'), ('04', 'Geita'), ('05', 'Iringa'), ('06', 'Kagera'), ('07', 'Katavi'), ('08', 'Kigoma'), ('09', 'Kilimanjaro'), ('10', 'Lindi'), ('11', 'Manyara'), ('12', 'Mara'), ('13', 'Mbeya'), ('14', 'Morogoro'), ('15', 'Mtwara'), ('16', 'Mwanza'), ('17', 'Njombe'), ('18', 'Pemba North'), ('19', 'Pemba South'), ('20', 'Pwani'), ('21', 'Rukwa'), ('22', 'Ruvuma'), ('23', 'Shinyanga'), ('24', 'Simiyu'), ('25', 'Singida'), ('26', 'Songwe'), ('27', 'Tabora'), ('28', 'Tanga'), ('29', 'Temeke'), ('30', 'Unguja North'), ('31', 'Unguja South'), ('32', 'Zanzibar City')], max_length=2)),
                ('collaborator_code', models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='agent_code',
            new_name='collaborator_code',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='agent_phone',
            new_name='collaborator_phone',
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(choices=[(1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], default=2025),
        ),
        migrations.AlterField(
            model_name='cases',
            name='file_path',
            field=models.FileField(upload_to='cases/files/'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
