# Generated by Django 5.1.4 on 2025-01-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_rename_plaintiff_cases_appellant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='appellant',
            new_name='appealant',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='defendant',
            new_name='respondant',
        ),
    ]
