# Generated by Django 5.1.3 on 2025-07-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_collaborator_delete_agent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='collaborator_code',
            new_name='collaborator_name',
        ),
    ]
