# Generated by Django 5.1.4 on 2025-02-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_rename_appellant_cases_appealant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='court_code',
            new_name='case_code',
        ),
    ]
