# Generated by Django 5.1.4 on 2025-02-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0017_rename_court_code_cases_case_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='appealant',
            new_name='appellant',
        ),
    ]
