# Generated by Django 5.1.4 on 2025-03-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0018_rename_appealant_cases_appellant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='tax_category',
            new_name='court',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='respondant',
            new_name='respondent',
        ),
    ]
