# Generated by Django 5.1.4 on 2025-03-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0019_rename_tax_category_cases_court_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='case_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
