# Generated by Django 5.2.3 on 2025-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0020_alter_cases_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
